In [1]:
import numpy as np

In [2]:
q1 = np.arange(1, 24, 2)
print("Q1:", q1)

Q1: [ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
q2 = np.linspace(5, 45, 9)
print("\nQ2:", q2)
print("Gap:", q2[1] - q2[0])



Q2: [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [4]:
q3_a = np.arange(1, 10)
q3_b = np.linspace(1, 9, 9)

print("\nQ3 arange:", q3_a)
print("Q3 arange dtype:", q3_a.dtype)

print("Q3 linspace:", q3_b)
print("Q3 linspace dtype:", q3_b.dtype)


Q3 arange: [1 2 3 4 5 6 7 8 9]
Q3 arange dtype: int64
Q3 linspace: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Q3 linspace dtype: float64


In [5]:
q4 = np.eye(6, dtype=int)
print("\nQ4:\n", q4)


Q4:
 [[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [6]:
q5 = np.full((3, 4), 5)

print("\nQ5:\n", q5)
print("Shape:", q5.shape)
print("Size:", q5.size)
print("Ndim:", q5.ndim)


Q5:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
Ndim: 2


In [7]:
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print("\nQ6:")
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)

b = b.astype(int)

print("b after astype:", b)
print("b dtype now:", b.dtype)
print("Types match:", a.dtype == b.dtype)



Q6:
a dtype: int64
b dtype: float64
b after astype: [2 4 6]
b dtype now: int64
Types match: True


In [8]:
q7 = np.array([10.9, 25.5, 39.99]).astype(int)

print("\nQ7:", q7)


Q7: [10 25 39]


In [9]:
arr = np.arange(10, 101, 10)

print("\nQ8 array:", arr)
print("4th element:", arr[3])
print("Last element:", arr[-1])
print("2nd-last element:", arr[-2])



Q8 array: [ 10  20  30  40  50  60  70  80  90 100]
4th element: 40
Last element: 100
2nd-last element: 90


In [10]:
print("\nQ9 selected:", arr[2:6])
print("Q9 reverse:", arr[::-1])


Q9 selected: [30 40 50 60]
Q9 reverse: [100  90  80  70  60  50  40  30  20  10]


In [11]:
arr2 = np.arange(1, 21)

q10 = arr2[1::3]

print("\nQ10:", q10)


Q10: [ 2  5  8 11 14 17 20]


In [12]:
q11 = arr2[2:-2]

print("\nQ11:", q11)



Q11: [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [13]:
m = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
print("\nQ12 3rd row:", m[2])
print("Q12 last column:", m[:, -1])
print("Q12 centre 3x3 block:\n", m[1:4, 1:4])



Q12 3rd row: [11 12 13 14 15]
Q12 last column: [ 5 10 15 20 25]
Q12 centre 3x3 block:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [14]:
q13 = m[::4, ::4]

print("\nQ13:\n", q13)



Q13:
 [[ 1  5]
 [21 25]]


In [15]:
q14 = m[::2, ::2]

print("\nQ14:\n", q14)



Q14:
 [[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [16]:
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
q15_a = marks[marks > 60]
q15_b = marks[(marks > 50) & (marks < 80)]

print("\nQ15 marks greater than 60:", q15_a)
print("Q15 marks between 50 and 80:", q15_b)


Q15 marks greater than 60: [91 77 62 85 70]
Q15 marks between 50 and 80: [56 77 62 70]
