In [22]:
import numpy as np
import pandas as pd

In [23]:
marks = np.array([
    [88, 96, 95],
    [72, 99, 91],
    [98, 85, 97],
    [60, 75, 80]
])

bonus = np.array([5, 2, 8])
marks = marks + bonus
capped_count = np.sum(marks > 100)
marks = np.minimum(marks, 100)

print("Updated marks:")
print(marks)

print("Number of capped marks:", capped_count)

Updated marks:
[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Number of capped marks: 4


In [24]:
matrix = np.ones((5, 5), dtype=int)

matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [25]:
arr = np.arange(30)
result = arr.reshape(5, -1).T

print("Shape:", result.shape)
print(result)

Shape: (6, 5)
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [26]:
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])
first = np.hstack((heights, weights))

print("First shape:", first.shape)
print(first)
table = np.column_stack((heights, weights))

print("\nProper table shape:", table.shape)
print(table)

First shape: (8,)
[172 158 181 166  68  52  84  59]

Proper table shape: (4, 2)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]


In [27]:
sales = np.array([
    120, 135, 98,
    160, 175, 190,
    88, 92, 105,
    210, 198, 230
])

quarters = sales.reshape(4, 3)

averages = quarters.mean(axis=1)

highest_quarter = np.argmax(averages)

print("Quarters:")
print(quarters)

print("Quarter averages:", averages)
print("Highest quarter index:", highest_quarter)
print("Highest average:", averages[highest_quarter])

Quarters:
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
Quarter averages: [117.66666667 175.          95.         212.66666667]
Highest quarter index: 3
Highest average: 212.66666666666666


In [28]:
a = np.array([2, 3, 4])

table = a.reshape(-1, 1) * a

print(table)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


In [29]:
arr = np.arange(1, 21)

arr[arr % 3 == 0] = -1

print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


In [30]:
x = np.array([
    [50, 1200, 3],
    [80, 1500, 9],
    [65, 900, 5],
    [95, 2000, 7]
])

col_min = x.min(axis=0)
col_max = x.max(axis=0)

normalized = (x - col_min) / (col_max - col_min)

print(normalized)

print("Column minimums:", normalized.min(axis=0))
print("Column maximums:", normalized.max(axis=0))

[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]
Column minimums: [0. 0. 0.]
Column maximums: [1. 1. 1.]


In [31]:
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(
    scores >= 90,
    "Gold",
    np.where(
        scores >= 75,
        "Silver",
        np.where(
            scores >= 60,
            "Bronze",
            "None"
        )
    )
)

print(medals)

print("Gold:", np.sum(medals == "Gold"))
print("Silver:", np.sum(medals == "Silver"))
print("Bronze:", np.sum(medals == "Bronze"))
print("None:", np.sum(medals == "None"))

['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Gold: 2
Silver: 2
Bronze: 2
None: 2


In [32]:
m = np.array([
    [10, 80, 45],
    [55, 20, 99],
    [70, 33, 12]
])
rows, cols = np.where(m > 50)

print("Rows:", rows)
print("Columns:", cols)

print("Elements greater than 50:", m[m > 50])
new_m = np.where(m > 50, 0, m)

print("New matrix:")
print(new_m)

print("Original matrix:")
print(m)

Rows: [0 1 1 2]
Columns: [1 0 2 0]
Elements greater than 50: [80 55 99 70]
New matrix:
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
Original matrix:
[[10 80 45]
 [55 20 99]
 [70 33 12]]


In [33]:
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])
rows = np.vstack((s1, s2, s3))
columns = np.column_stack((s1, s2, s3))

print("Rows:")
print(rows)

print("Shape:", rows.shape)

print("\nColumns:")
print(columns)

print("Shape:", columns.shape)

print("\nTranspose check:", np.array_equal(rows.T, columns))

Rows:
[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
Shape: (3, 5)

Columns:
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
Shape: (5, 3)

Transpose check: True


In [34]:
np.random.seed(1)

matrix = np.random.randint(1, 101, (6, 6))

row_max = matrix.max(axis=1)
column_min = matrix.min(axis=0)

print("Matrix:")
print(matrix)

print("\nRow-wise maximum:")
print(row_max)

print("\nColumn-wise minimum:")
print(column_min)

Matrix:
[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]

Row-wise maximum:
[76 80 85 69 97 64]

Column-wise minimum:
[ 7  8 17  2 19  6]


In [35]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9],
    [1, 0, 2]
])

result1 = A @ B.T
result2 = A.T @ B

print("A @ B.T:")
print(result1)
print("Shape:", result1.shape)

print("\nA.T @ B:")
print(result2)
print("Shape:", result2.shape)

A @ B.T:
[[ 50   7]
 [122  16]]
Shape: (2, 2)

A.T @ B:
[[11  8 17]
 [19 16 28]
 [27 24 39]]
Shape: (3, 3)


In [36]:
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])
hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

print("Hours shape:", hours_col.shape)
print("Attendance shape:", attendance_col.shape)
table = np.hstack((hours_col, attendance_col))

print("Table shape:", table.shape)
totals = table.sum(axis=1, keepdims=True)

print("Totals shape:", totals.shape)
three_col = np.hstack((table, totals))

print("Three-column shape:", three_col.shape)
print(three_col)
w = np.array([0.5, 0.2, 0.3])

scores = three_col @ w

print("Scores shape:", scores.shape)
print("Scores:", scores)
average = scores.mean()

result = np.where(scores > average, 1, 0)

print("Average:", average)
print("Final result:", result)
print("Final shape:", result.shape)

Hours shape: (6, 1)
Attendance shape: (6, 1)
Table shape: (6, 2)
Totals shape: (6, 1)
Three-column shape: (6, 3)
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
Scores shape: (6,)
Scores: [29.1 52.4 39.  57.  32.4 48.1]
Average: 43.0
Final result: [0 1 0 1 0 1]
Final shape: (6,)


In [37]:
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [38]:
m = np.array([
    [4, 8, 15],
    [16, 23, 42]
])

flat = m.flatten()
rav = m.ravel()

flat[0] = 999
rav[0] = 888

print("Original matrix:")
print(m)

Original matrix:
[[888   8  15]
 [ 16  23  42]]


In [39]:
np.random.seed(7)

temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)

weekly_average = weeks.mean(axis=1)

hottest_week = np.argmax(weekly_average)

days_above_35 = np.sum(temps > 35)

print("Weeks:")
print(weeks)

print("\nWeekly averages:")
print(weekly_average)

print("\nHottest week index:", hottest_week)

print("Hottest week average:", weekly_average[hottest_week])

print("Days above 35:", days_above_35)

Weeks:
[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]

Weekly averages:
[30.85714286 31.57142857 23.28571429 26.85714286]

Hottest week index: 1
Hottest week average: 31.571428571428573
Days above 35: 7


In [40]:
np.random.seed(10)

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

AB = A @ B
BA = B @ A

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA @ B:")
print(AB)

print("\nB @ A:")
print(BA)

print("\nAre they equal?", np.array_equal(AB, BA))

A:
[[5 1 2]
 [1 2 9]
 [1 9 7]]

B:
[[5 4 1]
 [5 7 9]
 [2 9 5]]

A @ B:
[[ 34  45  24]
 [ 33  99  64]
 [ 64 130 117]]

B @ A:
[[ 30  22  53]
 [ 41 100 136]
 [ 24  65 120]]

Are they equal? False


In [41]:
marks = np.array([
    [45, 28, 67, 80],
    [33, 90, 55, 41],
    [72, 66, 30, 58],
    [88, 79, 91, 84],
    [25, 40, 38, 52]
])
marks = np.maximum(marks, 35)
totals = marks.sum(axis=1)
topper_index = np.argmax(totals)

print("Updated marks:")
print(marks)

print("\nTotals:")
print(totals)

print("\nTopper index:", topper_index)
print("Topper total:", totals[topper_index])

Updated marks:
[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]

Totals:
[227 221 231 342 165]

Topper index: 3
Topper total: 342


In [42]:
arr = np.arange(1, 11)

slice_array = arr[2:6]
copy_array = arr[2:6].copy()

slice_array[0] = 999
copy_array[0] = 999

print("Original array:")
print(arr)

print("\nSlice:")
print(slice_array)

print("\nCopy:")
print(copy_array)

Original array:
[  1   2 999   4   5   6   7   8   9  10]

Slice:
[999   4   5   6]

Copy:
[999   4   5   6]


In [43]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
diagonal = np.diag(matrix)

print("Diagonal:")
print(diagonal)
arr = np.array([10, 20, 30, 40])

diagonal_matrix = np.diag(arr)

print("\nDiagonal matrix:")
print(diagonal_matrix)

Diagonal:
[ 1  6 11 16]

Diagonal matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
